instruments:
  # Акции
  # SBER:
  #   type: stock
  #   stop_loss_pct: 0.4        # Индивидуальный стоп-лосс 1.5%
  #   take_profit_pct: 1.0      # Индивидуальный тейк-профит 4%
    
  # GAZP:
  #   type: stock
  #   stop_loss_pct: 2.5        # Индивидуальный стоп-лосс 2.5%
  #   take_profit_pct: 6.0      # Индивидуальный тейк-профит 6%
    
  # Фьючерсы
  SiH5:  # Фьючерс на USD/RUB
    type: futures
    stop_loss_pct: 1.0        # 1% стоп-лосс (новый подход - в процентах)
    take_profit_pct: 2.5      # 2.5% тейк-профит (новый подход - в процентах)
    multi_tp:                 # Индивидуальная настройка многоуровневого TP
  #     enabled: true
  #     levels:
  #       - level_pct: 0.5      # +0.5% от средней цены
  #         volume_pct: 30      # Закрыть 30% позиции
  #       - level_pct: 1.0      # +1% от средней цены
  #         volume_pct: 30      # Закрыть 30% позиции
  #       - level_pct: 1.5      # +1.5% от средней цены
  #         volume_pct: 40      # Закрыть 40% позиции
          
  # RIH5:  # Фьючерс на индекс РТС
  #   type: futures
  #   stop_loss_pct: 1.5        # 1.5% стоп-лосс (новый подход - в процентах)
  #   take_profit_pct: 3.0      # 3% тейк-профит (новый подход - в процентах)
    
  # BRJ5:  # Фьючерс на нефть Brent
  #   type: futures
  #   stop_loss_steps: 20       # 20 шагов цены (старый подход - для обратной совместимости)
  #   take_profit_steps: 50     # 50 шагов цены (старый подход - для обратной совместимости)
